version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=118 --verbose=1 --configuration=/opt/opendlv.data/configuration"

    odcockpit:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/opt/opendlv.data
        - ~/recordings:/opt/recordings
        ipc: host
        user: odv
        depends_on:
          - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=118"

    cfsd18-sensation-attention:
        image: "attention:test"
        network_mode: "host"
        ipc: host
        command: "cfsd18-sensation-attention --cid=118 --verbose --id=116 --xBoundary=4 --yBoundary=12 --groundLayerZ=-0.3 --coneHeight=1 --connectDistanceThreshold=0.4 --layerRangeThreshold=0.06 --minNumOfPointsForCone=2 --maxNumOfPointsForCone=80 --farConeRadiusThreshold=0.2 --nearConeRadiusThreshold=0.25 --zRangeThreshold=0.08 --inlierRangeThreshold=0.06 --dotThreshold=0.1 --inlierFoundThreshold=150 --numberOfIterations=10"

    cfsd18-perception-detectcone:
        image: "detectcone:test"
        network_mode: "host"
        ipc: host
        working_dir: /opt
        environment:
          - DISPLAY=$DISPLAY
        volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
         - ./tmp:/opt
         - "/dev/shm:/dev/shm"
         # - ../images:/opt/images/
         # - ../timestamp:/opt/timestamp/
        # depends_on:
        #   - proxy-camera
        ulimits:
          memlock:
            soft: 5600000 #1516032
            hard: 5600000
        command: "cfsd18-perception-detectcone --cid=118 --name=cam0 --width=2560 --height=720 --bpp=24 --verbose --id=1 --threshold=1.5 --timeDiffMilliseconds=20 --checkLidarMilliseconds=1000 --senderStamp=118 --attentionSenderStamp=116, --offline=1, --annotate=0"

    # proxy-camera:
    #     image: producer:latest #cproxy:cproxyv1
    #     network_mode: host
    #     group_add:
    #         - video
    #     ipc: host
    #     devices:
    #         - "/dev/video1:/dev/video0"
    #     environment:
    #         - DISPLAY=$DISPLAY
    #     volumes:
    #         - /tmp/.X11-unix:/tmp/.X11-unix
    #         - "/dev/shm:/dev/shm"
    #     ulimits:
    #       memlock:
    #         soft: 5600000 #1516032
    #         hard: 5600000
    #     command: "opendlv-device-camera-opencv --name=cam0 --bgr2rgb --cid=118 --camera=/dev/video0 --width=2560 --height=720 --bpp=24 --freq=15 --verbose"

    # cfsd18-perception-imagerecorder:
    #     image: "imgrec:imgrecv0"
    #     network_mode: "host"
    #     ipc: host
    #     volumes:
    #     - ./images:/opt/images
    #     - ./timestamp:/opt/timestamp/
    #     depends_on:
    #       - proxy-camera
    #     command: "cfsd18-perception-imagerecorder --cid=${CID} --name=cam0 --width=2560 --height=720 --bpp=24 --verbose --id=1"

    
