# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-16

version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    #signal-viewer
    signal-viewer:
        image: chalmersrevere/opendlv-signal-viewer-multi:v0.0.7
        network_mode: "host"
        ports:
            - "8080:8080" 
        command: "--cid=${CID}"

    #vehicle-viewer
    vehicle-viewer:
       image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.16
       network_mode: "host"
       ports:
           - "8081:8081" 
       command: "--cid=${CID}"

    cfsd18-sensation-attention:
        image: "attention:test"
        network_mode: "host"
        ipc: host
        command: "cfsd18-sensation-attention --cid=${CID} --verbose --id=116 --xBoundary=4 --yBoundary=12 --groundLayerZ=-0.3 --coneHeight=0.5 --connectDistanceThreshold=0.4 --layerRangeThreshold=0.06 --minNumOfPointsForCone=2 --maxNumOfPointsForCone=80 --farConeRadiusThreshold=0.2 --nearConeRadiusThreshold=0.25 --zRangeThreshold=0.08 --inlierRangeThreshold=0.06 --dotThreshold=0.1 --inlierFoundThreshold=150 --numberOfIterations=10"

    cfsd18-perception-detectcone:
        image: "detectcone:test"
        network_mode: "host"
        ipc: host
        working_dir: /opt
        environment:
          - DISPLAY=$DISPLAY
        volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
         - .:/opt
         - "/dev/shm:/dev/shm"
         - ../usecases/Recording/Recording3/images:/opt/images/
         - ../usecases/Recording/Recording3/timestamp:/opt/timestamp/
         - ./results:/opt/results
        # depends_on:
        #   - proxy-camera
        ulimits:
          memlock:
            soft: 5600000 #1516032
            hard: 5600000
        command: "cfsd18-perception-detectcone --cid=${CID} --name=cam0 --width=1344 --height=376 --bpp=24 --verbose --id=1 --threshold=1.5 --timeDiffMilliseconds=20 --separationTimeMs=10 --checkLidarMilliseconds=1000 --senderStamp=118 --attentionSenderStamp=116 --offline=1 --annotate=0"

    odcockpit:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ~/recordings:/opt/recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}" 

   


